### ISSUE TITLE
WiPy TODO list

### ISSUE THREAD

**Issue by danicampora** [micropython/micropython#1425]
Hello,

So here it is, a list of things that we have to decide before shipping the WiPy's to the backers. Shipping will begin on the last week of August, but, I have to program the boards before that, not that I'm trying to hurry anyone... ;-)

- [ ] Pin API (Almost clear what to do), see #1408.
- [ ] Power management and reset API (pyb ?? modmachine??), see #1297
- [ ] Callback API, see #1118
- [ ] WLAN API, see #876

I think it's best to continue each discussion in the original tickets and just put the conclusions here for reference.

**Comment by danicampora** [comment]
Closing, done in #1430.
