### ISSUE TITLE
Prepare for v1.6

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#1803]
It's time again for the next release, which will be v1.6.  It should be released this weekend.  Things on the list:

- ~~[ ] addition of mpytool.py to inspect .mpy files~~
- ~~[ ] ability to use mpytool.py to freeze .mpy files so precompiled Python code can be executed from flash (basically this is "true" frozen modules, although I think it's good to keep the existing "frozen script" frozen modules as well)~~
- [x] merge #1713 (stmhal CDC improvements)
- [x] merge #1799 (unix printf fix)
- [x] unix port segfault #1787
- [x] stmhal I2C bus errors with DMA: #1683 #1765

**Comment by pfalcon** [comment]
> although I think it's good to keep the existing "frozen script" frozen modules as well

I hope yes, until .mpy use will become widespread ;-).

**Comment by dpgeorge** [comment]
> although I think it's good to keep the existing "frozen script" frozen modules as well
> 
> I hope yes, until .mpy use will become widespread ;-).

Also because it's (currently) a complicated issue to get a uPy cross compiler built for the target.  It's nice to be able to freeze raw text files: it just works.

**Comment by dpgeorge** [comment]
mpy files and persistent bytecode is too big a change and will need to wait for next version (but is available at #1811 for those wanting to try it out).

**Comment by dpgeorge** [comment]
v1.6 has been tagged here: 331a48195d325b9557175056e2c3650ef496d862
