### ISSUE TITLE
Prepare for release v1.9.3

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython#3346]
Since v1.9.2 the major change was a move to the "ports/" directory layout and that seems to be OK, so would be good to tag a new version.

Things to potentially resolve before tagging (this list may be edited):
- [ ] #3122 alloca/VLA issue
- [ ] #3291 clean up opcode enums (?)
- [x] #3331 math domain checking
- [x] #3334 null bytes
- [x] #3344 clean up opcode enums and bump .mpy version
- [x] #3361 building with MINGW - commit that broke MINGW was reverted

**Comment by robert-hh** [comment]
+1 on #3122 I understand it makes the code more robust
no opinion on finish cleaning up opcode enums
+1 on #3331 Even if no one complained about it so far. It's just consistent

**Comment by dmazzella** [comment]
> plans to implement what is written in the uos.dupterm TODO?
// TODO should accept any object with read / write methods.

@dpgeorge Yes, that will be worked on soon.

News about this? Can be this released in 1.9.3?

**Comment by dpgeorge** [comment]
@dmazzella In commit d6bf3658f44e22f06e0d293b8fe0542b57538b4f I made os.dupterm() on pyboard allow to take any object with write/readinto methods.  pyb.repl_uart() still behaves as before so if you want the new functionality please use os.dupterm(obj).

**Comment by dmazzella** [comment]
@dpgeorge thank you, try it as soon as possible.

**Comment by paganopaganino** [comment]
@dpgeorge where i can find example of use for os.dupterm?

**Comment by dpgeorge** [comment]
Ok, this release was delayed a bit.  I wanted to look properly into #3122 (VLA stuff) and will attempt to do that in the coming days.  But if it's looking like it will take too long then I'll move to release v1.9.3 ASAP and postpone #3122 until after.

**Comment by chrismas9** [comment]
@dpgeorge, I have been slowed down by a knee replacement. I should be back on #3361 this week.

**Comment by dpgeorge** [comment]
@chrismas9 at this point I'm inclined to revert 3289b9b7a76a1230b6bb631e191a47bfc6c7a8ee so that I can do the v1.9.3 release and that it doesn't have any regressions.  Then after that the issue of compiling under Windows can be revisited.

**Comment by chrismas9** [comment]
@dpgeorge, that's fine. I'm back at work now, but it's probably best to test it thoroughly without time pressure.

**Comment by dpgeorge** [comment]
Thanks @chrismas9 , I've now reverted it.

The outstanding VLA issue requires some deeper changes to do it correctly so I'll postpone that until after v1.9.3.

I will tag and release v1.9.3 within the next 12 hours or so, should be by UTC 23:59, 31st Oct 2017.

**Comment by dpgeorge** [comment]
Ok, v1.9.3 was tagged in fe45d78b1edd6d2202c3544797885cb0b12d4f03, see release at https://github.com/micropython/micropython/releases/tag/v1.9.3

The esp-extra-scripts branch was rebased on top of v1.9.3 and force-pushed.
